using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;

namespace AllInOneAPI.Models
{
    public class EnrollerDetail
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        public string Id { get; set; }

        public int EnrolllerType { get; set; }

        public string Body { get; set; } = string.Empty;

        [BsonDateTimeOptions]
        public DateTime UpdatedOn { get; set; } = DateTime.UtcNow;

        public EnrollerImage HeaderImage { get; set; }

        public int UserId { get; set; } = 0;

        public string Email { get; set; }

        public string MobileNumber { get; set; }
    }
}
