using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json;
using System;

namespace AllInOneAPI.Models
{
    public class FRResponseDetail
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        [JsonProperty("Body")]
        public string Body { get; set; } = string.Empty;

        public string OCRDateTime { get; set; }

        public string ImageReLocation { get; set; }

        public string ImageFTPPath { get; set; }

        [JsonProperty("CameraIpAddress")]
        public string CameraIpAddress { get; set; }

        [JsonProperty("CameraName")]
        public string CameraName { get; set; }

    }
}
